version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: book_api_db
    environment:
      POSTGRES_USER: user_api
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: